---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# rOpenSci Reviews

<!-- badges: start -->
<!-- badges: end -->


## Reviews

- Package [qualR](https://github.com/quishqa/qualR)
  - [Issue](https://github.com/ropensci/software-review/issues/474)
  - [Report](https://github.com/beatrizmilz/ropensci_reviews/blob/main/review-qualR/README.md)
  - [Review](https://github.com/ropensci/software-review/issues/474#issuecomment-981622813)
  

- Package [frictionless-r](https://github.com/frictionlessdata/frictionless-r)
  - [Issue](https://github.com/ropensci/software-review/issues/495)
  - [Report](https://github.com/beatrizmilz/ropensci_reviews/blob/main/frictionless/review.md)
  - [Review](https://github.com/ropensci/software-review/issues/495#issuecomment-1025860861)  



## How to start a new review:

```{r eval=FALSE, include=TRUE}
# Install pkgreviewr
# remotes::install_github("ropensci-org/pkgreviewr")

# Create the structure for the review
pkgreviewr::pkgreview_create(pkg_repo = "nameoforg/nameofpackage", 
                 review_parent = ".")
```
